### ISSUE TITLE
Researching possible hosting solutions

### ISSUE THREAD

**Issue by cbaudouinjr** [noonalu/noonalu-backend#1]
We need to find a solution to host our MVP. This doesn't have to be a permanent solution.

**Comment by peterkos** [comment]
https://mobile.twitter.com/Ak_Mittal/status/1567175784229650432

> Now that Heroku free tier is not available, here are a few alternatives 
Serverless and edge functions: Deno, Vercel, Netlify, Cloudflare.
Databases:. Planetscale, Supabase, Cockroach, Fauna, Upstash.
Services:. Fly, Railway, Render.

**Comment by cbaudouinjr** [comment]
The best option for the MVP is Dokku with a t3.micro EC2 tier from AWS. This includes 750 hours/month of free usage which is more than we need to run a basic backend. We'll revaluate this solution for v1.0.0.
