### ISSUE TITLE
Create a random identifier for each calendar

### ISSUE THREAD

**Issue by cbaudouinjr** [noonalu/noonalu-backend#15]
Each calendar should not only have a unique ID, but a random ID as well. This will help prevent users from navigating to other calendars and modifying the data.

**Acceptance Criteria**
- UUIDs should resemble the form `a1b2c3d4`
- UUIDs shout NOT be the form `0001`

**Comment by JeremyRudman** [comment]
This is somewhat done for us in mongodb with the autogenerated [objectId ](https://www.mongodb.com/docs/manual/reference/method/ObjectId/) value for id. Based on my understanding of the documentation the risk of a user accessing another calendar though going up/down in id's is only really present if multiple calendars are made in the same second. The security hole may still be worth filling but then we will need a public Id and mongo's autogenerated built-in id.
